baseURL = "http://sam.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "SAM"
[markup.goldmark.renderer]
unsafe = true
# disable language
disableLanguages = ["de"]
